//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Design.java
//  @ Date : 2018-07-11
//  @ Author : 
//
//




public class Design {
	public Object color;
}
