//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Electronic.java
//  @ Date : 2018-07-11
//  @ Author : 
//
//




public interface Electronic {
/*	public Object Attribute1;
	public Object Attribute2;
	public Object Attribute3;
	public void Operation1();
	public void Operation2();*/
}
