//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Radio.java
//  @ Date : 2018-07-11
//  @ Author : 
//
//




public class Radio {
	private int volume = 0;
	public void setVolume(int v) {
	
	}
//
//	public int getVolume() {
//
//	}
	
	public void handling() {
	
	}
}
